services:
  db:
    platform: linux/x86_64
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: raicho_dev
    ports:
      - "5431:5432"
    env_file:
      - ./db/.env
volumes:
  db_data:
