import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import React, { FC } from 'react';
import './globals.css';

type Props = {
  children: React.ReactNode;
};

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ホーム | Raicho',
  description: 'Generated by create next app',
};

const RootLayout: FC<Props> = ({ children }) => {
  return (
    <html lang="ja">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
